export const zh = {
  title: "我该吃什么",
  settingData: "菜品管理",
  settingGet: "抽取设置",
  import: "导入",
  export: "导出",
  back: '返回',
  setting: "设置",
  maxKa: "预算(大卡)",
  maxKaPlaceholder: "输入一天的预算(大卡)",
  numDay: "几顿饭",
  numDayPlaceholder: "请输入一天吃几顿饭",
  save: "保存",
  namePlaceholder: "输入要添加的菜名",
  kaPlaceholder: "输入菜品能量(大卡)",
  add: "添加",
  name: '名称',
  energy:"能量(大卡)",
  action: "操作",
  getOne: "抽取一次",
  getPlan: "抽取一天菜单",
  clickToStart: "点击按钮开启抽取",
  saveSuccess: "保存成功！",
  importSuccess: "导入成功！",
  pickSuccess: "抽取成功！",
  delSuccess: "删除成功！",
  addSuccess: "添加成功！",
  pleaseAddMenu: "请先添加菜单！",
  pleaseSetPickConfig: "请先设置抽取配置！",
  ka: "大卡",
  mustBeNumber: "请填入数字！",
  total: "总计",
  remove: "删除"
}

export const en = {
  title: "What to eat",
  settingData: "Menu Management",
  settingGet: "Pick Settings",
  import: "Import",
  export: "Export",
  back: 'Back',
  setting: "Settings",
  maxKa: "Budget (Kcal)",
  maxKaPlaceholder: "Enter a day's budget (kcal)",
  numDay: "Number of Meals",
  numDayPlaceholder: "Please enter how many meals to eat a day",
  save: "Save",
  namePlaceholder: "Enter the name of the dish to be added",
  kaPlaceholder: "Input dish energy (kcal)",
  add: "Add",
  name: 'Name',
  energy:"Energy (Kcal)",
  action: "Action",
  getOne: "Pick Once",
  getPlan: "Pick A Day Menu",
  clickToStart: "Click button to start",
  saveSuccess: "Save Success!",
  importSuccess: "Import Success!",
  pickSuccess: "Pick Success!",
  addSuccess: "Add Success!",
  delSuccess: "Remove Success!",
  pleaseAddMenu: "Please add menu first!",
  pleaseSetPickConfig: "Please set pick settings first!",
  ka: "Kcal",
  mustBeNumber: "Please input number!",
  total: "Total",
  remove: "Remove"



}